### ISSUE TITLE
Documentation incorrectly references ProductionEnvironment

### ISSUE THREAD

**Issue by kweiberth** [paypal/Checkout-NodeJS-SDK#14]
Not sure this is the best place to raise this issue, but there's a comment in the [sample code here](https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/#set-up-the-environment) that references `ProductionEnvironment`, but it should be `LiveEnvironment`.

**Comment by rajarampadmanathan** [comment]
Hi @kweiberth - Thank you for reporting this. We will update the documentation to reflect the correct name.

**Comment by erksch** [comment]
I think it would be great to make it more visible in the sample code. It's very easy to miss right now.
I would suggest something like this:

```
function environment() {
    let clientId = process.env.PAYPAL_CLIENT_ID || 'PAYPAL-SANDBOX-CLIENT-ID';
    let clientSecret = process.env.PAYPAL_CLIENT_SECRET || 'PAYPAL-SANDBOX-CLIENT-SECRET';

    // Use LiveEnvironment for production.
    return new checkoutNodeJssdk.core.SandboxEnvironment(
        clientId, clientSecret
    );
}
```

Or even 

```
function environment() {
    let clientId = process.env.PAYPAL_CLIENT_ID || 'PAYPAL-SANDBOX-CLIENT-ID';
    let clientSecret = process.env.PAYPAL_CLIENT_SECRET || 'PAYPAL-SANDBOX-CLIENT-SECRET';

    if (process.env.NODE_ENV === 'production') {
       return new checkoutNodeJssdk.core.LiveEnvironment(clientId, clientSecret);
    }

    return new checkoutNodeJssdk.core.SandboxEnvironment(clientId, clientSecret);
}
```
Because your code will end up something like this anyway.
But this presumes that the developer correctly sets his NODE_ENV variable.

**Comment by rbcabreraUPM** [comment]
Please update the docs. I was testing the production environment and got the same error.

**Comment by gfranco93** [comment]
This has just happened to me. Please update the docs, it's a quick fix.

**Comment by ganeshramc** [comment]
Hey this should be updated by next week!

**Comment by ganeshramc** [comment]
This is fixed now in the documentation. Thanks!
