### ISSUE TITLE
NPM is listed as a regular dependancy

### ISSUE THREAD

**Issue by sr-scott** [paypal/Checkout-NodeJS-SDK#15]
Looking at the code I can't see an obvious reason why `npm` is being listed as a core dependancy and not as a dev dependancy?

Noticed it because it introduces a dependency with a security vulnerability that was flagged up in our CI pipeline.

I'm not entirely sure why it's listed at all for a Node.js application as `npm` is distributed with Node. I haven't seen this done before. Would be interested to know if this is for a specific reason?

Cheers in advance.

**Comment by rajarampadmanathan** [comment]
Hi.. Thanks for reporting this. I will check this and update you.
