### ISSUE TITLE
Arbitrary File Overwrite vulnerabilities when installing @paypal/checkout-server-sdk

### ISSUE THREAD

**Issue by okba1** [paypal/Checkout-NodeJS-SDK#16]
Hello, 

I have just installed @paypal/checkout-server-sdk using npm and I get 4 high severity vulnerabilities related to Arbitrary File Overwrite. Could you please check this?
Here is the complete report:

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  High            Arbitrary File Overwrite

  Package         tar

  Patched in      >=4.4.2

  Dependency of   @paypal/checkout-server-sdk

  Path            @paypal/checkout-server-sdk > npm > libcipm > npm-lifecycle
                  > node-gyp > tar

  More info       https://nodesecurity.io/advisories/803

  High            Arbitrary File Overwrite

  Package         tar

  Patched in      >=4.4.2

  Dependency of   @paypal/checkout-server-sdk

  Path            @paypal/checkout-server-sdk > npm > libnpm > npm-lifecycle >
                  node-gyp > tar

  More info       https://nodesecurity.io/advisories/803

  High            Arbitrary File Overwrite

  Package         tar

  Patched in      >=4.4.2

  Dependency of   @paypal/checkout-server-sdk

  Path            @paypal/checkout-server-sdk > npm > node-gyp > tar

  More info       https://nodesecurity.io/advisories/803

  High            Arbitrary File Overwrite

  Package         tar

  Patched in      >=4.4.2

  Dependency of   @paypal/checkout-server-sdk

  Path            @paypal/checkout-server-sdk > npm > npm-lifecycle > node-gyp
                  > tar

  More info       https://nodesecurity.io/advisories/803

found 4 high severity vulnerabilities in 12357 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

**Comment by JoelRicharte** [comment]
found 12 high severity vulnerabilities
"Tar" and "fstream" packages

**Comment by ganeshramc** [comment]
This should be fixed with the new merge on develop!
