### ISSUE TITLE
12 high severity vulnerabilities

### ISSUE THREAD

**Issue by wviveiro** [paypal/Checkout-NodeJS-SDK#19]
It seems there are 12 high severity vulnerabilities in the @paypal/checkout-server-sdk. Is it going to be fixed?

 === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libcipm > npm-lifecycle  │
│               │ > node-gyp > fstream                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libcipm > npm-lifecycle  │
│               │ > node-gyp > tar > fstream                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libnpm > npm-lifecycle > │
│               │ node-gyp > fstream                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libnpm > npm-lifecycle > │
│               │ node-gyp > tar > fstream                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > node-gyp > fstream       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > node-gyp > tar > fstream │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > npm-lifecycle > node-gyp │
│               │ > fstream                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fstream                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.12                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > npm-lifecycle > node-gyp │
│               │ > tar > fstream                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/886                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libcipm > npm-lifecycle  │
│               │ > node-gyp > tar                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > libnpm > npm-lifecycle > │
│               │ node-gyp > tar                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > node-gyp > tar           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2 <3.0.0 || >=4.4.2                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @paypal/checkout-server-sdk                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @paypal/checkout-server-sdk > npm > npm-lifecycle > node-gyp │
│               │ > tar                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by ganeshramc** [comment]
If you clone this repo directly the vulnerabilities shouldn't come up. We haven't released an update to npm yet.

**Comment by wviveiro** [comment]
Great, I will do that then.... Thanks @ganeshramc !

**Comment by rajarampadmanathan** [comment]
Released `1.0.1` version with fix for this issue. Please validate and let us know in case of any issues.
https://www.npmjs.com/package/@paypal/checkout-server-sdk/v/1.0.1

**Comment by wviveiro** [comment]
No vulnerabilities found, 

Problem solved guys! thanks!
