### ISSUE TITLE
Generic Error "UkVUUlk%3D" - no useful redirection after payment selection

### ISSUE THREAD

**Issue by NikRet** [paypal/Checkout-NodeJS-SDK#24]
In the beginning i create my example order with the following code snippet. The order creation is successful and the response is correct.

```
const paypalRequest: any = {};
    paypalRequest.intent = "CAPTURE";
    paypalRequest.purchase_units = [{
      amount: {
        value: "239.00",
        currency_code: "EUR",
        breakdown: {
          item_total: {
            value: "239.00",
            currency_code: "EUR"
          },
          tax_total: {
            value: "0.00",
            currency_code: "EUR"
          }
        }
      },
      items: [{
        name: "TestItem",
        unit_amount: {
          currency_code: "EUR",
          value: "239.00"
        },
        quantity: "1",
        tax: {
          currency_code: "EUR",
          value: "0.00"
        },
        description: "test item description",
        category: "DIGITAL_GOODS",
        payee: {
          email_address: "service@touridat.de"
        }
      }]
    }];

    const paypalOrder = await paypalCheckoutComponent.createOrder(paypalRequest);
```

After the creation i redirect  to the checkout page and the payment selection appears. If I select any payment, not important which kind, the ui reloads and renders the payment selection again without any response.
If I try to select a payment again, the error page appears and in the url is the generic error code "UkVUUlk%3D".

It would be nice if you can tell me some information about this error code or show me where i did the mistake :)

**Comment by rajarampadmanathan** [comment]
Hi, 

Are you passing the return and cancel url ? If yes can you provide the debug Id?

https://developer.paypal.com/docs/api/orders/v2/#definition-application_context

**Comment by NikRet** [comment]
Hey,

yes i pass the return and cancel url but it makes no difference.

Debug ID: f9185712aaec1

**Comment by rajarampadmanathan** [comment]
in the above snippet i don't see the return and cancel URL. Also, it is not present in the request which we received. Can you please post the complete request which you're sending with return and cancel URL?

**Comment by NikRet** [comment]
Okay, sorry. Here's the full request:

```
const paypalRequest: any = {};
    paypalRequest.intent = "CAPTURE";
    paypalRequest.purchase_units = [{
      amount: {
        value: "239.00",
        currency_code: "EUR",
        breakdown: {
          item_total: {
            value: "239.00",
            currency_code: "EUR"
          },
          tax_total: {
            value: "0.00",
            currency_code: "EUR"
          }
        }
      },
      items: [{
        name: "TestItem",
        unit_amount: {
          currency_code: "EUR",
          value: "239.00"
        },
        quantity: "1",
        tax: {
          currency_code: "EUR",
          value: "0.00"
        },
        description: "test item description",
        category: "DIGITAL_GOODS",
        payee: {
          email_address: "service@touridat.de"
        }
      }],
       application_context: {
         return_url: "www.touridat.de",
         cancel_url: "www.google.com",
         brand_name: "TouriDat GmbH & Co. KG",
         locale: "de-DE",
      }
    }];

    const paypalOrder = await paypalCheckoutComponent.createOrder(paypalRequest);
```

**Comment by rajarampadmanathan** [comment]
Do you the debug id for this full request?

**Comment by NikRet** [comment]
The id should be one of the ids below, it was always the same request:

f9185712aaec1
e0896ace12b74
e5f5a3842cff3

**Comment by rajarampadmanathan** [comment]
Looks like you’re passing application_context at wrong path. It should not be inside purchase unit.

It should be parallel to purchase unit.

**Comment by NikRet** [comment]
Oh hell thank you, it works correct now.
Thanks for your help and have a nice day :)
