### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by akleiber** [paypal/Checkout-NodeJS-SDK#25]
Hello there,

are there any TypeScript definitions available? 
I searched for`@types/paypal__checkout-server-sdk`.

**Comment by bennymeg** [comment]
I don't think they wrote TS definitions for that package. =/

I think right question is if they are planning to write TS definitions for that package, and if so, when are planning to release it.

For that kind of API, I think that is mandatory..

**Comment by piavgh** [comment]
+1
I'm switching my project to Typescript and I need this package also

**Comment by richardscarrott** [comment]
I'm guessing [these types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/paypal-rest-sdk/paypal-rest-sdk-tests.ts) aren't for this package?

I find understanding what is what within the PayPal ecosystem is a nightmare -- never know if the docs I'm reading are talking about the code I'm writing!

Would be great to know if there is a plan to ship types as if there isn't I'm sure somebody in the community would be happy to create them on DefinitelyTyped.

**Comment by rwieruch** [comment]
I am here for TS support as well 🚀

**Comment by tiboprea** [comment]
These types would definitely come in handy for anyone using Typescript. +1

**Comment by tolstenko** [comment]
+1 I am here for it too

**Comment by fandy** [comment]
+1 typings would be amazing. Working with the JS SDK is a PITA right now. When creating an order, missing one small thing in the config object throws unhelpful errors.

**Comment by rogerbaockt** [comment]
+1

**Comment by mkarpusiewicz** [comment]
+1

**Comment by raman-nbg** [comment]
@rajarampadmanathan can give an update? Are there any plans? The community is waiting for almost a year now. :(

**Comment by gatsbyz** [comment]
hello

**Comment by rsdighe76** [comment]
We do not have plans to define TypeScripts definitions. If things change in the future we will post an update.
