### ISSUE TITLE
braintree http package / state of this package

### ISSUE THREAD

**Issue by akleiber** [paypal/Checkout-NodeJS-SDK#26]
Hi,

is this repo meant to be used in production? Or should we use https://github.com/paypal/PayPal-node-SDK if the 2.0.0 release is finished?

The https://github.com/braintree/braintreehttp_node is a beta version (0.4.0) and the GitHub repo is archived. Why using something like that?

**Comment by tiffanyrzhou** [comment]
This sdk can be used in production environment.We are no longer using the briantreehttp. The braintreehttp package was replaced with the paypalhttp package in November 2019.
