### ISSUE TITLE
Question on creating subscription and receiving payments

### ISSUE THREAD

**Issue by WayneUong** [paypal/Checkout-NodeJS-SDK#27]
I follow this guide to create plan and subscription: https://developer.paypal.com/docs/subscriptions/integrate/

How do I check when payments are made? For the old plan/agreement API, I can use webhook events to track payments. But the new subscription doesn't seen to generate payments, or at least not right away. Is the payment only coming at the end of the cycle now? I can see a payment event was sent when if an initial fee is set, but it's associated with an agreement, and not a subscription.

I'm very confused there's no resource on handling payments for subscription??

**Comment by rsdighe76** [comment]
this SDK does not support this particular API - it only supports v2/payments and v2/checkout/orders
