### ISSUE TITLE
Paypal / Checkout-NodeJS Error

### ISSUE THREAD

**Issue by AbouNasr** [paypal/Checkout-NodeJS-SDK#28]
This call:
const checkoutNodeJssdk = require('C:/Data/Developpement/Web3Ddev/node_modules/@paypal/checkout-server-sdk');
let Request = new checkoutNodeJssdk.orders.OrdersGetRequest(orderID);

generates the following error:
{ Error: {"name":"RESOURCE_NOT_FOUND","details":[{"location":"path","issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"87e21b2787e81","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]}
    at IncomingMessage.response.on (C:\Data\Developpement\Web3Ddev\node_modules\braintreehttp\lib\braintreehttp\http_client.js:106:22)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Any idea about the RESOURCE_ID?
Thanks

**Comment by ganeshramc** [comment]
Hi abounasr, this normally means that the orderID you are passing is invalid or non existent. Resource refers to order id.
On Jul 18, 2019, 22:44 -0700, AbouNasr <notifications@github.com>, wrote:

This call:
const checkoutNodeJssdk = require('C:/Data/Developpement/Web3Ddev/node_modules/@paypal/checkout-server-sdk');
let Request = new checkoutNodeJssdk.orders.OrdersGetRequest(orderID);

generates the following error:
{ Error: {"name":"RESOURCE_NOT_FOUND","details":[{"location":"path","issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"87e21b2787e81","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]}
at IncomingMessage.response.on (C:\Data\Developpement\Web3Ddev\node_modules\braintreehttp\lib\braintreehttp\http_client.js:106:22)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1129:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

Any idea about the RESOURCE_ID?
Thanks

**Comment by AbouNasr** [comment]
Thanks for your prompt reponse.
the orderID: 4F111558GC4076359 has been generated with:
    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
            // Set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: amount
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Call your server to save the transaction
                    return fetch('/paypal-transaction-complete', {
                        method: 'post',
                        headers: {'content-type': 'application/json'},
                        body: JSON.stringify({ orderID: data.orderID})
            });
                });
            }
        }).render('#paypal-button-container');
    </script>

**Comment by ganeshramc** [comment]
Thank you! From our side it seems like the order id does not exist. This could be possible because you are creating order with one client id and secret but trying to capture it with something else.

**Comment by AbouNasr** [comment]
This could be the problem?
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=EUR"></script>

**Comment by AbouNasr** [comment]
sb&currency=EUR

**Comment by ganeshramc** [comment]
This could be an issue. It's currently late night for us so will talk to my team since it's not part of the SDK itself and update you on this issue. Thanks!

**Comment by AbouNasr** [comment]
Thank you very much

**Comment by rajarampadmanathan** [comment]
Hi @AbouNasr - Looks like you're using different client id in SPB client (For create order) and different client id in server side integration (get order). Can you please check by using the asme client id/secret in both both the calls?

**Comment by ganeshramc** [comment]
Hi @AbouNasr, adding on to @rajarampadmanathan's comments, it could be possible that you created two different apps which would result in different client id's and you used a different one for the smart payment button integration and another one for the get order.

**Comment by AbouNasr** [comment]
Right!!! I solved the problem this morning, and it works very well.
Thank very much for putting me on the right way. 
Should I close the issue?

**Comment by ganeshramc** [comment]
Awesome. Glad we could help! I will close this issue! Please reach out with any other questions :)

**Comment by doohab** [comment]
I get the same error, and I checked the client id in both files are the same. how to debug what's wrong?
