### ISSUE TITLE
Can add "No Shipping" Option in API ?

### ISSUE THREAD

**Issue by xjoyzaza** [paypal/Checkout-NodeJS-SDK#29]
like classic API
[requiredSecurityParameters]
&METHOD=SetExpressCheckout
&RETURNURL=https://...
&CANCELURL=https://...
&PAYMENTREQUEST_0_AMT=10.00
&PAYMENTREQUEST_0_CURRENCYCODE=USD
&PAYMENTREQUEST_0_PAYMENTACTION=Sale
`&NOSHIPPING=1`
&PAYMENTREQUEST_0_SHIPTONAME=J Smith
&PAYMENTREQUEST_0_SHIPTOSTREET=1 Main St
&PAYMENTREQUEST_0_SHIPTOCITY=San Jose
&PAYMENTREQUEST_0_SHIPTOSTATE=CA
&PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE=US
&PAYMENTREQUEST_0_SHIPTOZIP=95131
&PAYMENTREQUEST_0_SHIPTOPHONENUM=555-123-4444

**Comment by xjoyzaza** [comment]
solved by just add "shipping_preference": "NO_SHIPPING",  in application_context

**Comment by ganeshramc** [comment]
Awesome glad to know you were able to fix your issue!
