### ISSUE TITLE
v2 payment status "partially refunded" during open dispute

### ISSUE THREAD

**Issue by jamiefuller96** [paypal/Checkout-NodeJS-SDK#31]
After a buyer opens a dispute on PayPal via the Resolution Centre. I query the v2 payment capture and notice that the status changes from "COMPLETE" to "PARTIALLY_REFUNDED".

From reading the docs, I would expect to see the payment status change to "PENDING" with a new status_details object with the value "BUYER_COMPLAINT"

https://developer.paypal.com/docs/api/payments/v2/#definition-capture_status_details

This is observed in the Sandbox environment.

**Comment by jamiefuller96** [comment]
I am subscribed to the dispute webhook but it should not matter. 

The scenario is:

1. Buyer opens dispute (any reason: item not received etc..) via resolution centre,
2. The status of the payment capture being disputed immediately changes from "COMPLETED" to "PARTIALLY_REFUNDED" as soon as a dispute is opened.

The payment status is misleading, as a refund or partial refund has not been given at this stage so the payment capture should be "Held" or "Under Review" or "Pending" or something to show it is currently held in the dispute process.

if the case is closed with seller favour then status returns to "Completed" as expected.

Same if case is closed because seller issues full refund to customer, then status changes to "Refunded" as expected.


To reproduce:

1. Open a dispute case via resolution centre with a transaction.
2. Query the payment status /v2/payments/captures/{capture_id} API and observe the payment capture status.

**Comment by tiffanyrzhou** [comment]
Hi @jamiefuller96. We will look into reproducing this issue. If you have any paypal-debug-id, you can share in regards with this issue that would be great. Thanks

**Comment by tiffanyrzhou** [comment]
@jamiefuller96 We were able to identify this error. The fix would be in the API.
