### ISSUE TITLE
What is the difference between this library and https://www.npmjs.com/package/paypal-rest-sdk ?

### ISSUE THREAD

**Issue by piavgh** [paypal/Checkout-NodeJS-SDK#32]
Hi everyone,

I'm a bit confused after checking Paypal documentation.

There are 2 libraries:

1. https://www.npmjs.com/package/@paypal/checkout-server-sdk (which is this repo)

2. https://www.npmjs.com/package/paypal-rest-sdk (Github repo: https://github.com/paypal/PayPal-node-SDK)

In this guide https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/, Paypal suggests that we use `@paypal/checkout-server-sdk`

So when we need to use `paypal-rest-sdk` ? Or they are the same / one is the dependency of the other?

**Comment by ganeshramc** [comment]
For v2 orders you would use checkout-server-sdk whereas for v1 payments you would use paypal-rest-sdk!

**Comment by piavgh** [comment]
> For v2 orders you would use checkout-server-sdk whereas for v1 payments you would use paypal-rest-sdk!

Thank you for your information.
Can you please give me the reference link for v1 and v2 that you referred? Paypal document is a little bit confused

**Comment by ganeshramc** [comment]
Yes! For orders v2, please check https://developer.paypal.com/docs/api/orders/v2/
For payments v1, please check https://developer.paypal.com/docs/api/payments/v1/
This SDK is for orders v2 and https://github.com/paypal/PayPal-node-SDK is for payments v1
