### ISSUE TITLE
Parse error response

### ISSUE THREAD

**Issue by richardscarrott** [paypal/Checkout-NodeJS-SDK#33]
It appears this lib is really just here to handle auth transparently which is great, but I wonder if it could also parse the error response as currently it requires accessing and parsing a pseudo-private property [`_originalError`](https://github.com/braintree/braintreehttp_node/blob/master/lib/braintreehttp/http_client.js#L23) on the [`HttpError`](https://github.com/braintree/braintreehttp_node/blob/master/lib/braintreehttp/http_client.js#L16) from [braintreehttp](https://github.com/braintree/braintreehttp_node)

I imagine it's a v. common task for developers to [read error codes](https://developer.paypal.com/docs/api/orders/v2/#errors).

**Comment by rsdighe76** [comment]
We will take it up as feedback.
