### ISSUE TITLE
Missing 'PayPal-Auth-Assertion' header?

### ISSUE THREAD

**Issue by dsoegijono** [paypal/Checkout-NodeJS-SDK#39]
As a partner managing transaction refunds, we're required to send this header. However, it doesn't seem to be implemented [here](https://github.com/paypal/Checkout-NodeJS-SDK/blob/develop/lib/payments/capturesRefundRequest.js)?

**Comment by stukker01** [comment]
You can modify the headers as mentioned in the documentation: https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/#http-request-headers
