### ISSUE TITLE
Problems with authentication (Was working before)

### ISSUE THREAD

**Issue by Dyceman** [paypal/Checkout-NodeJS-SDK#40]
`{ Error: {"error":"internal_error","error_description":"Connection time out during load_user_data"}
    at IncomingMessage.response.on (D:\WebstormProjects\rkstore-web\node_modules\@paypal\paypalhttp\lib\paypalhttp\http_client.js:136:22)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   '{"error":"internal_error","error_description":"Connection time out during load_user_data"}',
  statusCode: 500,
  headers:
   { 'cache-control': 'max-age=0, no-cache, no-store, must-revalidate',
     'content-length': '90',
     'content-type': 'application/json',
     date: 'Wed, 25 Mar 2020 08:16:27 GMT',
     'paypal-debug-id': 'b99680a0dd3d5',
     'x-paypal-token-service': 'IAAS',
     'x-slr-retry': '500',
     'x-slr-retry-api': '/v1/oauth2/token',
     connection: 'close' },
  _originalError:
   { text:
      '{"error":"internal_error","error_description":"Connection time out during load_user_data"}',
     statusCode: 500,
     headers:
      { 'cache-control': 'max-age=0, no-cache, no-store, must-revalidate',
        'content-length': '90',
        'content-type': 'application/json',
        date: 'Wed, 25 Mar 2020 08:16:27 GMT',
        'paypal-debug-id': 'b99680a0dd3d5',
        'x-paypal-token-service': 'IAAS',
        'x-slr-retry': '500',
        'x-slr-retry-api': '/v1/oauth2/token',
        connection: 'close' } } }
`

**Comment by rsdighe76** [comment]
does this continue to happen? - please reopen the issue if it does and we will look into it.
