### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by RamoSterious** [paypal/Checkout-NodeJS-SDK#43]
So I was working on the previous version with is the PayPal-REST-SDK and it just stopped working and now I cannot find any documentation on how to do subscriptions on this SDK is there any links or any samples I can view?

**Comment by rsdighe76** [comment]
This SDK Is not a replacement for the PayPal-REST-SDK it supports only v2/checkout/orders and v2/payments.

**Comment by PierreCapo** [comment]
@rsdighe76 Thanks for the response.
If this checkout SDK is not a replacement for for the PayPal-REST-SDK and the REST one has a deprecation notice: 
https://github.com/paypal/PayPal-node-SDK

Does it mean we should use a deprecated sdk for subscription ?
