### ISSUE TITLE
No payment_source returned when capture

### ISSUE THREAD

**Issue by PB12203006** [paypal/Checkout-NodeJS-SDK#44]
Is there anyway I can get `payment_source` when I do `OrdersCaptureRequest` ?
According to this documentation, the response is supposed to contain this field
https://developer.paypal.com/docs/api/orders/v2/#orders_capture
But I only get the same data as your README, there's no `payment_sourcde` even if I set 
```javascript
    const request = new payPal.orders.OrdersCaptureRequest(orderId);
    request.prefer('return=representation');
```
Can someone please help me?

**Comment by tiffanyrzhou** [comment]
Hi @PB12203006 If the capture request isn't sending payment_source details, the payment source isn't returned. The payment_source detail isn't required in the capture request, in the case the checkout process is completed through the PayPal web experience. 
For further input, please share your correlation-id  in the header of the capture response.

**Comment by PB12203006** [comment]
@tiffanyrzhou  Appreciate your help! I would suggest updating the documentation either here or on paypal's API doc.

will close the issue now
